services:
  - type: web
    name: vidyazen-school-management
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.1
  - type: pserv
    name: vidyazen-mysql
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.mysql
    disk:
      name: vidyazen-mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1